motion_compliance_site_force:
  _target_: isaaclab.managers.ObservationTermCfg
  func: gear_sonic.compliance_control.adapters.sonic.mdp:motion_compliance_site_force
  params:
    command_name: motion_compliance
